title: NSS Software Engineering Jumpstart
description: NSS Software Engineering Jumpstart

remote_theme: NSS-Software-Engineering/nss-just-the-docs

# These settings are in the nss-just-the-docs _config.yml file, but seem to be ingored.
#  NOTE: The logo.png file IS in the theme, we just have to reference it in the site config
logo: "/assets/images/logo.png"
color_scheme: nss
aux_links_new_tab: true
aux_links:
  "NSS Software Engineering":
    - "https://se.nashss.com"
footer_content: "<a href='https://nashvillesoftwareschool.com'>Nashville Software School</a>"
url: "https://se-jumpstart.nashss.com"
permalink: pretty

ga_tracking: G-5PZ2V6XBVV

# We only want to publish session1 prework to Github Pages
include: [
  index.md, 
  sessions/session1/prework,
  sessions/session1/classroom/installations.md]
exclude: [
  README.md, Gemfile, Gemfile.lock,

  sessions/session1/classroom/begin_hello_world.gif,
  sessions/session1/classroom/end_hello_world.gif,
  sessions/session1/classroom/exercise_madlibs.md,
  sessions/session1/classroom/golden_girls.gif,
  sessions/session1/classroom/hello_world.md,
  sessions/session1/classroom/interactivity.md,
  sessions/session1/classroom/intro_to_tools.md,
  sessions/session1/classroom/lightning_exercises.md,
  sessions/session1/classroom/mad_libs.svg,
  sessions/session1/classroom/orientation.md,
  sessions/session1/classroom/session1_lightning.svg,

  sessions/session1/wrapup/*,
  sessions/session2/**,
  sessions/session3/**,
  sessions/session4/**,
  sessions/session5/**,
  sessions/session6/**,
  sessions/session7/**,
  sessions/session8/**,
  sessions/session9/**,
  sessions/next-steps/**,
  reference/**, 
  projects/**]
